parameters:
    tchoulom.view_counter.base.class: Tchoulom\ViewCounterBundle\Service\AbstractViewCounter
    tchoulom.view_counter.class: Tchoulom\ViewCounterBundle\Service\ViewCounter

services:
    tchoulom.view_counter.base:
        class: '%tchoulom.view_counter.base.class%'
        abstract:  true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
            - '%view_interval%'

    tchoulom.view_counter:
        class: '%tchoulom.view_counter.class%'
        parent: tchoulom.view_counter.base