parameters:
    tchoulom.view_counter.base.class: Tchoulom\ViewCounterBundle\Counter\AbstractViewCounter
    tchoulom.view_counter.class: Tchoulom\ViewCounterBundle\Counter\ViewCounter
    tchoulom.view_counter.persister.base.class: Tchoulom\ViewCounterBundle\Persister\AbstractPersister
    tchoulom.view_counter.persister.class: Tchoulom\ViewCounterBundle\Persister\Persister

services:
    tchoulom.view_counter.base:
        class: '%tchoulom.view_counter.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@tchoulom.view_counter.persister'
            - '@request_stack'
            - '%view_interval%'

    tchoulom.view_counter:
        class: '%tchoulom.view_counter.class%'
        public: true
        parent: tchoulom.view_counter.base

    tchoulom.view_counter.persister.base:
        class: '%tchoulom.view_counter.persister.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    tchoulom.view_counter.persister:
        class: '%tchoulom.view_counter.persister.class%'
        public: true
        parent: tchoulom.view_counter.persister.base